---
title: "Analisis de Muchos Modelos"
# params: 
#   output_dir: "../../reports/"
#params:
#  encoding: "latin1"
output:
  pdf_document:
    keep_tex: yes
    #df_print: paged
    latex_engine: pdflatex
    pandoc_args: "--listings"
  html_notebook:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
    df_print: paged
  html_document:
    keep_md: TRUE
    toc: true
    theme: united
    toc_float: yes
    df_print: paged
author: "Sebastian Jaremczuk"
date: 2020-04-17
# always_allow_html: true # esto es para que siempre permita html por los widgets pero no anda bien el kable ... usar webshot y phantomjs (tampo anduvo bien)
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, message = FALSE, warning = FALSE)

```


```{r}
# para que los widget los tome como printscreen cdo hace df
# install.packages("webshot")
# webshot::install_phantomjs()
```



```{r include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(stringr)
library(glue)

```

```{r include=FALSE}

getwd()
path_base = '/home/rstudio/desercion/'
# saveRDS(config, paste0(path_base, config$outputs ,"config.rds"))
config = read_rds(paste0(path_base, "outputs/00_modelo_02/config.rds"))
```


```{r include=FALSE}
# cargo todas las librerias en la carpeta lib

librerias.proyecto.actual = list.files(path = paste0(path_base, 'lib'))
librerias.proyecto.actual = librerias.proyecto.actual[!(librerias.proyecto.actual %in% c("README.md","globals.R","helpers.R"))]
librerias.proyecto.actual = str_c(paste0(path_base, 'lib/'), librerias.proyecto.actual, sep = '' )
librerias.proyecto.actual = librerias.proyecto.actual[str_ends(librerias.proyecto.actual, pattern = ".R") | str_ends(librerias.proyecto.actual, pattern = ".r")]
# cargo las librerias
sapply(librerias.proyecto.actual, source)

```


### carga de datos


```{r}
datos_train_prep = read_rds(path = paste0(path_base, config$outputs, "baseline_2009_train_prep.rds") )
datos_test_prep = read_rds(path = paste0(path_base, config$outputs, "baseline_2009_test_prep.rds") )

```


```{r}
modelo_knn = read_rds(path = paste0(path_base, config$outputs, "modelo_knn.rds") )
modelo_nb = read_rds(path = paste0(path_base, config$outputs, "modelo_nb.rds") )
modelo_logistic = read_rds(path = paste0(path_base, config$outputs, "modelo_logistic.rds") )
modelo_lda = read_rds(path = paste0(path_base, config$outputs, "modelo_lda.rds") )
modelo_C50Tree = read_rds(path = paste0(path_base, config$outputs, "modelo_C50Tree.rds") )
modelo_rf = read_rds(path = paste0(path_base, config$outputs, "modelo_rf.rds") )
modelo_boost = read_rds(path = paste0(path_base, config$outputs, "modelo_boost.rds") )
modelo_svmrad = read_rds(path = paste0(path_base, config$outputs, "modelo_svmrad.rds") )
modelo_nnet = read_rds(path = paste0(path_base, config$outputs, "modelo_nnet.rds") )
```



```{r}

modelos <- list(KNN = modelo_knn, logistic = modelo_logistic,
                LDA = modelo_lda, rf = modelo_rf, arbol = modelo_C50Tree,
                boosting = modelo_boost, SVMradial = modelo_svmrad,
                NNET = modelo_nnet)

#  NB = modelo_nb, 

```



```{r}
library(caret)
library(randomForest)
library(ranger)
library(gbm)
library(klaR)
library(MASS)
library(C50)
library(kernlab)
library(nnet)


predicciones <- extractPrediction(
                  models = modelos,
                  testX = datos_test_prep[,which(colnames(datos_test_prep) != "deserto")],
                  testY = as.factor(datos_test_prep$deserto)
                  )
# predicciones %>% head()

# predict(modelo_nb, newdata = datos_test_prep, type = "raw") # no anda bien naivebayes
```

# KNN

```{r}

summary(modelo_knn)

cf_knn = confusionMatrix(data = predicciones %>% filter(object == "KNN") %>% 
                  filter(dataType == "Test") %>% pull(pred) ,
                reference = datos_test_prep %>% pull(deserto),
                positive = "1")

cf_knn


```

